replicaCount: 1

name: wpproxy

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

namespace: nginx-proxy

configMap:
  defaultConf: |
    server {
        listen 80;

        location / {
            proxy_pass http://wpapp.wpapp.svc.cluster.local:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
