apiVersion: v1
appVersion: 1.0.0
version: 1.0.0
name: wordpress-nginx
description: wordpress nginx proxy for wp stack
keywords:
  - wordpress
  - mariadb
  - nginx
maintainers:
  - name: Frank Chirapa
