apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/frankrodrigo/helmwp.git'
    targetRevision: HEAD
    path: wp
    helm:
      valueFiles:
        - dev/values.yaml
        - dev/secrets.enc.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wpapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
